### ISSUE TITLE
Cannot connect to local GitLab instance

### ISSUE THREAD

**Issue by Choens** [pweingardt/mylyn-gitlab#33]
At work, we are running a GitLab server behind a firewall. And, for whatever reason, the server is running Gitlab with http:// addresses rather than https:// addresses. There's nothing I can do about that.

I have a project on this server at the following URL:  http://appdev1/HealthHomes/HHCMART3.git
This URL works for EGit. I can push and pull to the project all day long.

But I cannot connect the GitLab MyLyn connector:

![image](https://cloud.githubusercontent.com/assets/424993/22300379/45703c5c-e2f5-11e6-9e9b-727a93066d61.png)

I erased my username / password from the image, but I've checked them umpteen times, and the error suggests it isn't a password issue. I'm wondering if anyone can either tell me what I'm doing wrong or if there's anything I can do to fix this. (Note: I'm not a Java developer, but if it isn't too hard, it would be a good excuse to remember how to write some Java.)

**Comment by samrocketman** [comment]
Is your URL literally, `http://appdev1/HealthHome/HHCMART3.git`?  It might have a URL validator that is tripping up on your host name.

**Comment by samrocketman** [comment]
It's not the URL pattern.  From [`ConnectionManager.java`](https://github.com/pweingardt/mylyn-gitlab/blob/master/de.weingardt.mylyn.gitlab.core/src/de/weingardt/mylyn/gitlab/core/ConnectionManager.java#L82-L85), I wrote a quick groovy script to validate the URL.

```groovy
import java.util.regex.Matcher
import java.util.regex.Pattern

Pattern URLPattern = Pattern.compile('((?:http|https)://(?:.*))/((?:[^\\/]*?)/(?:[^\\/]*?))$')

println "Pattern matches? ${URLPattern.matcher('http://appdev1/HealthHome/HHCMART3.git').find()}"
```

The output is:

```
Pattern matches? true
```

So it's not what I originally thought.

The [`GitLabExceptionHandler.java`](https://github.com/pweingardt/mylyn-gitlab/blob/master/de.weingardt.mylyn.gitlab.core/src/de/weingardt/mylyn/gitlab/core/exceptions/GitlabExceptionHandler.java#L19-L20) is catching a `FileNotFoundException` for the error message `Invalid path in host`.

In Java networking, `FileNotFoundException` exceptions typically occur with [HTTP 4XX errors](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4).  The problem is likely your URL is returning a 4XX HTTP error rather than actually interacting with a GitLab instance.

**Comment by Choens** [comment]
Agreed. I didn't write a validation script, kudos on that idea, but I agree. It seems as if Java is encountering a 4xx error. But EGit has the same weird URL, on the same client machine (my workstation) and I can push/pull using EGit and the Gonsole just fine.

How would I get the stack trace for this? 

Disclaimer - I'm a bit of a noob with Eclipse/Java. I've been experimenting with using Eclipse/DBeaver/Statet as an integrated workbench for what I do at work. I am . . . . considering . . .  the possibility that there may be more to life than Emacs.

**Comment by Choens** [comment]
OK. I played with this some more. I realized that when I had pushed to my repo, I was falling back on my emacs style way of doing things and using wicked shell. EGit was NOT pushing/pulling. Apologies for that. Your first conclusion was correct. I was getting a 4xx HTTP error. I don't understand why, but that is definitely what is happening. I replace "appdev1" with the IP Address, and Mylyn was able to connect.

Apologies for the errant bug report.
